### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by derekcat**
Added an optional line to filter to only display a group.  (All praise to eburgueno!)
Added OS lines for Ubuntu and Mac OS 10.6-11 (Yes, I know there's no OS 10.11.... Yet)

### CODE REVIEW

**Comment by eburgueno** [comment]
How about a checkbox option in the settings?
:ballot_box_with_check:Show Inventory Field

If ticked, we let the user specify the OS field in a text box. At a glance, people might use anything between Type, Type (Full details), Name, Alias, OS, OS (Full details), OS (Short). Instead of us collectively trying to describe every single OS out there, we can let the end-used do the job.

As a plus, this would encourage users to properly configure their items and inventory fields in Zabbix :)

**Comment by derekcat** [comment]
Hey Velinath,
Thanks!  Yeah, the view model is definitely the best solution, but IMHO the groupids line is a pretty good stopgap measure until the view model is running. ^_^

Eburgueno,
Prompting the users to choose a field is a great idea, though I'd like to still try to parse the regular os field as completely as we can.  I can see someone with a large install complaining that they don't want to fill in os_full for some ridiculous number of servers.

**Comment by eburgueno** [comment]
> I can see someone with a large install complaining that they don't want to fill in os_full for some ridiculous number of servers.

Actually, they don't need to. You can automatically populate inventory fields based on the value of any item of your choice. If you click on an item, you should see a 'Populates Host Inventory Field'.
I have *'system.uname'* populating my 'OS Full', but you could easily have (for example) an item with key *'system.run[uname]'* that will return "Linux" for linux servers, and make it populate OS, or OS (short), or whatever (note that 'system.run[]' requires EnableRemoteCommands=1 in you zabbix_agentd.conf).

> I'd like to still try to parse the regular os field as completely as we can.

The problem that I see with that approach is that we can't possibly know what the user is doing with their Zabbix inventory, if anything at all. The more generic the solutions we adopt, the easier for us to maintain, and the more users who can use the tool out of the box.

**Comment by velinath** [comment]
ref #13 for implementing groupid in the future - going to merge this

**Pull request merged**
